export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const POST_LOADING = 'POST_LOADING';
export const ADD_POST= 'ADD_POST';
export const GET_POST = 'GET_POST';
export const GET_POSTS = 'GET_POSTS';
export const DELETE_POST = 'DELETE_POST';


export const SET_CURRENT_COMPANY = 'SET_CURRENT_COMPANY';
export const GET_PORTFOLIO = 'GET_PORTFOLIO';
export const PORTFOLIO_LOADING = 'PORTFOLIO_LOADING';
export const PORTFOLIO_NOT_FOUND = 'PORTFOLIO_NOT_FOUND';
export const CLEAR_CURRENT_PORTFOLIO = 'CLEAR_CURRENT_PORTFOLIO';
export const GET_PORTFOLIOS = 'GET_PORTFOLIOS';


